Fix consistency with indentation

diff --git a/upstream-watch b/upstream-watch
--- a/upstream-watch
+++ b/upstream-watch
@@ -19,7 +19,7 @@ fi
 
 log() {
     if [ -n "$VERBOSE" ]; then
-    echo "$*"
+        echo "$*"
     fi
 }
 
@@ -27,16 +27,16 @@ update_package_list() {
     log "[i] Updating package list"
     :> $WORKDIR/list
     for component in main contrib non-free; do
-    wget -q $MIRROR/dists/$DIST/$component/source/Sources.gz -O - | \
-        gzip -dc >> $WORKDIR/list
+        wget -q $MIRROR/dists/$DIST/$component/source/Sources.gz -O - | \
+            gzip -dc >> $WORKDIR/list
     done
 }
 
 list_packages() {
     if [ -e "$PACKAGE_LIST" ]; then
-    grep -v '^#' $PACKAGE_LIST
+        grep -v '^#' $PACKAGE_LIST
     else
-    sed -n 's/^Package: //p' $WORKDIR/list
+        sed -n 's/^Package: //p' $WORKDIR/list
     fi
 }
 
@@ -56,45 +56,45 @@ dsc_url() {
 extract_watch_files() {
     log "[i] Extracting all watch files"
     for package in $(list_packages); do
-    if ! grep -q "Package: $package" $WORKDIR/list; then
-        echo "WARNING: $package is not available in $DIST" >&2
-        continue
-    fi
-    version=$(extract_field $package Version)
-    if grep -q ${package}_${version} $WORKDIR/extracted; then
-        continue
-    fi
-    url=$(dsc_url $package)
-    log "Extracting watch file from $url"
-    cd $WORKDIR/tmp
-    if ! dget -q -u -d $url; then
-        echo "ERROR: downloading source package from $url" >&2
-    fi
-    cd $BASEDIR
-    filename="$WORKDIR/tmp/$(basename $url)"
-    target="$WORKDIR/watchfiles/$package"
-    set +e
-    dscextract -f $filename debian/watch > ${target}.new
-    result=$?
-    set -e
-    rm -f $WORKDIR/tmp/*
-    case $result in
-        0)
-        sed -i -e 's/pgpsigurlmangle=s[^, ]*/active/' ${target}.new
-        mv ${target}.new $target
-        ;;
-        1)
-        rm -f ${target}.new $target
-        ;;
-        *)
-        rm -f ${target}.new
-        echo "ERROR: extracting debian/watch from $filename" >&2
-        return
-        ;;
-    esac
-    grep -v "^${package}_" $WORKDIR/extracted > $WORKDIR/extracted.new || true
-    mv $WORKDIR/extracted.new $WORKDIR/extracted
-    echo "${package}_${version}" >> $WORKDIR/extracted
+        if ! grep -q "Package: $package" $WORKDIR/list; then
+            echo "WARNING: $package is not available in $DIST" >&2
+            continue
+        fi
+        version=$(extract_field $package Version)
+        if grep -q ${package}_${version} $WORKDIR/extracted; then
+            continue
+        fi
+        url=$(dsc_url $package)
+        log "Extracting watch file from $url"
+        cd $WORKDIR/tmp
+        if ! dget -q -u -d $url; then
+            echo "ERROR: downloading source package from $url" >&2
+        fi
+        cd $BASEDIR
+        filename="$WORKDIR/tmp/$(basename $url)"
+        target="$WORKDIR/watchfiles/$package"
+        set +e
+        dscextract -f $filename debian/watch > ${target}.new
+        result=$?
+        set -e
+        rm -f $WORKDIR/tmp/*
+        case $result in
+            0)
+                sed -i -e 's/pgpsigurlmangle=s[^, ]*/active/' ${target}.new
+                mv ${target}.new $target
+                ;;
+            1)
+                rm -f ${target}.new $target
+                ;;
+            *)
+                rm -f ${target}.new
+                echo "ERROR: extracting debian/watch from $filename" >&2
+                return
+                ;;
+        esac
+        grep -v "^${package}_" $WORKDIR/extracted > $WORKDIR/extracted.new || true
+        mv $WORKDIR/extracted.new $WORKDIR/extracted
+        echo "${package}_${version}" >> $WORKDIR/extracted
     done
 }
 
@@ -113,11 +113,11 @@ extract_upstream_version() {
     local version=$1
     new=$(expr "$version" : '[0-9]\+:\(.*\)' || true)
     if [ -n "$new" ]; then
-    version=$new
+        version=$new
     fi
     new=$(expr "$version" : '\(.*\)-[^-]*' || true)
     if [ -n "$new" ]; then
-    version=$new
+        version=$new
     fi
     echo $version
 }
@@ -132,8 +132,8 @@ dump_uscan_data() {
     echo " STDOUT: "
     sed -e 's/^/ /' $WORKDIR/tmp/uscan-stdout
     if [ -s $WORKDIR/tmp/uscan-stderr ]; then
-    echo " STDERR: "
-    sed -e 's/^/ /' $WORKDIR/tmp/uscan-stderr
+        echo " STDERR: "
+        sed -e 's/^/ /' $WORKDIR/tmp/uscan-stderr
     fi
 }
 
@@ -142,7 +142,7 @@ record_status() {
     local status=$2
     current=$(grep "^$1 " $WORKDIR/status | cut -d" " -f2)
     if [ "$current" = "$status" ]; then
-    return
+        return
     fi
     # Fill out the report when something changed
     version=$(extract_field $package Version)
@@ -173,38 +173,38 @@ record_status() {
 check_new_upstream_versions() {
 	log "[i] Checking for updates"
     for package in $(list_packages); do
-    if [ ! -e $WORKDIR/watchfiles/$package ]; then
-        log "WARNING: $package has no watch file in $DIST" >&2
-        record_status $package MISSING
-        continue
-    fi
-    version=$(extract_field $package Version)
-    debian_uversion=$(extract_upstream_version $version)
-    run_uscan $package $debian_uversion > $WORKDIR/tmp/uscan-stdout 2> $WORKDIR/tmp/uscan-stderr || true
-    status=$(get_uscan_field status)
-    upstream_version=$(get_uscan_field upstream-version)
-    upstream_url=$(get_uscan_field upstream-url)
-    case "$status" in
-        "Newer version available"|"newer package available")
-        log "NEW: $package $upstream_version at $upstream_url"
-        status="OUTDATED_$upstream_version"
-        ;;
-        "up to date"|"Debian version newer than remote site"|"only older package available")
-        log "INFO: $package is $status"
-        status="OK"
-        ;;
-        "")
-        log "BROKEN: $package"
-        log "$(dump_uscan_data)"
-        status="BROKEN"
-        ;;
-        *)
-        echo "ERROR: unknown output uscan status: $status" >&2
-        log "$(dump_uscan_data)"
-        status="BROKEN"
-        ;;
-    esac
-    record_status "$package" "$status" "$upstream_version" "$upstream_url"
+        if [ ! -e $WORKDIR/watchfiles/$package ]; then
+            log "WARNING: $package has no watch file in $DIST" >&2
+            record_status $package MISSING
+            continue
+        fi
+        version=$(extract_field $package Version)
+        debian_uversion=$(extract_upstream_version $version)
+        run_uscan $package $debian_uversion > $WORKDIR/tmp/uscan-stdout 2> $WORKDIR/tmp/uscan-stderr || true
+        status=$(get_uscan_field status)
+        upstream_version=$(get_uscan_field upstream-version)
+        upstream_url=$(get_uscan_field upstream-url)
+        case "$status" in
+            "Newer version available"|"newer package available")
+                log "NEW: $package $upstream_version at $upstream_url"
+                status="OUTDATED_$upstream_version"
+                ;;
+            "up to date"|"Debian version newer than remote site"|"only older package available")
+                log "INFO: $package is $status"
+                status="OK"
+                ;;
+            "")
+                log "BROKEN: $package"
+                log "$(dump_uscan_data)"
+                status="BROKEN"
+                ;;
+            *)
+                echo "ERROR: unknown output uscan status: $status" >&2
+                log "$(dump_uscan_data)"
+                status="BROKEN"
+                ;;
+        esac
+        record_status "$package" "$status" "$upstream_version" "$upstream_url"
     done
 }
 
@@ -219,22 +219,22 @@ setup_workdir() {
 send_report() {
     log "[i] Generating report"
     if [ ! -s $WORKDIR/report ]; then
-    log "REPORT: Nothing new to report."
-    exit 0
+        log "REPORT: Nothing new to report."
+        exit 0
     fi
 
     if [ -n "$MAILTO" ]; then
-    log "REPORT: Sent by mail to $MAILTO"
-    cat - $WORKDIR/report <<-END | mail -s "Upstream watch status for $DIST" $MAILTO
-    Hello,
+        log "REPORT: Sent by mail to $MAILTO"
+        cat - $WORKDIR/report <<-END | mail -s "Upstream watch status for $DIST" $MAILTO
+        Hello,
 
-    The following changes have been detected while running uscan
-    on all the watch files tracked in $DIST:
+        The following changes have been detected while running uscan
+        on all the watch files tracked in $DIST:
 
 END
     else
-    log "REPORT: The following changes have been detected"
-    cat $WORKDIR/report
+        log "REPORT: The following changes have been detected"
+        cat $WORKDIR/report
     fi
 }
 
