Revert "Don't die if a dsc file isn't available."
This reverts commit 0814e25b4633a74a7fcde49ddce88213040c9063.

This was incorrect, and was checking the echo statement, so revert.

diff --git a/upstream-watch b/upstream-watch
--- a/upstream-watch
+++ b/upstream-watch
@@ -68,7 +68,7 @@ extract_watch_files() {
         log "Extracting watch file from: $url"
         cd $WORKDIR/tmp
         if ! dget -q -u -d $url; then
-            echo "ERROR: downloading source package from: $url" >&2 || true
+            echo "ERROR: downloading source package from: $url" >&2
         fi
         cd $BASEDIR
         filename="$WORKDIR/tmp/$(basename $url)"
